export const Keywords = [
    { name: "Advance" },
    { name: "Allegiance" },
    { name: "Attack" },
    { name: "Attune", icon: "Attune" },
    { name: "Augment", icon: "Augment" },
    { name: "Aura", icon: "Aura" },
    { name: "Barrier", icon: "Barrier" },
    { name: "Behold" },
    { name: "Blockade", specialIndicator: "can't take damage or die" },
    { name: "Burst", icon: "Burst" },
    { name: "Can block Elusives", specialIndicator: 'can block units with Elusive' },
    { name: "Can't Attack", icon: "Can't Attack", specialIndicator: "Immobile" },
    { name: "Can't Block", icon: "Can't Block", specialIndicator: "Immobile" },
    { name: "Capture", icon: "Capture" },
    { name: "Challenger", icon: "Challenger" },
    { name: "Countdown" },
    { name: "Daybreak" },
    { name: "Deep", icon: "Deep" },
    { name: "Double Attack", icon: "Double Attack" },
    { name: "Drain" },
    { name: "Elusive", icon: "Elusive" },
    { name: "Enlightened" },
    { name: "Ephemeral", icon: "Ephemeral" },
    { name: "Everywhere", icon: "Ephemeral" },
    { name: "Fast", icon: "Fast" },
    { name: "Fearsome", icon: "Fearsome" },
    { name: "Fleeting", icon: "Fleeting" },
    { name: "Focus", icon: "Focus" },
    { name: "Frostbite", icon: "Frostbite" },
    { name: "Fury", icon: "Fury" },
    { name: "Imbue", icon: "Imbue" },
    { name: "Invoke", icon: "Invoke" },
    { name: "Last Breath", icon: "Last Breath" },
    { name: "Lifesteal", icon: "Lifesteal" },
    { name: "Nab" },
    { name: "Nexus Strike" },
    { name: "Nightfall" },
    { name: "Obliterate" },
    { name: "Phase" },
    { name: "Play" },
    { name: "Plunder" },
    { name: "Predict" },
    { name: "Quick Attack", icon: "Quick Attack" },
    { name: "Rally", icon: "Rally" },
    { name: "Recall" },
    { name: "Reforge" },
    { name: "Regeneration", icon: "Regeneration" },
    { name: "Reputation" },
    { name: "Restore the Sun Disc", specialIndicator: 'SunDiscRestore' },
    { name: "Round End" },
    { name: "Round Start" },
    { name: "Scout", icon: "Scout" },
    { name: "Silence", icon: "Silence" },
    { name: "Slay" },
    { name: "Slow", icon: "Slow" },
    { name: "SpellShield", icon: "SpellShield" },
    { name: "Strike" },
    { name: "Strongest" },
    { name: "Stun", icon: "Stun" },
    { name: "Support", icon: "Support" },
    { name: "Toss" },
    { name: "Tough", icon: "Tough" },
    // { name: "Trigger", icon: "Trigger" },
    { name: "Vulnerable", icon: "Vulnerable" },
    { name: "Weakest" },
]